### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Ispirett**
Thanks your time

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @Ispirett  and @Macatuz ,

`rspec` not working for this project. It shows me no example found. I don't understand why `test.rb` need for this project. In this project, you have to test the main methods of a class. In an example, suppose you have a `Game` class. Now think about it which method should be a test. I assume that there is a method in which check is there any draw. That means this is an important method to test is it working the way you want to make it. Also, I noticed that you used a lot `relative`. So I will recommend you to first understand where you should use `require` and `require_relative` and then implement this. Here is an [article](https://medium.com/@ellishim/understanding-require-vs-require-relative-vs-require-all-80e3b26d89e6). You can also review it if there is any better documentation or tutorials about it. I also suggest you write separate test cases in separate files. Like if you wanna test `Game` class methods then create a file `game_spec.rb` and write all the test cases inside it. Do the same thing for all the classes and module you want to test.

After fixing this send another request to review this project.

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @Ispirett and @Macatuz ,

So far so good. But still, this shouldn't be shown with the `rspec` test report.


- `rspec -f doc spec\gui_spec.rb` is not working.
- `rspec -f doc spec\game_manager_spec.rb` not working
- Use let for [this ](https://github.com/Ispirett/Rspec-Tic-Tac-Toe/blob/227254dcbecfaff1d4f196d08737cce580fe563b/spec/board_spec.rb#L6-L13), [this](https://github.com/Ispirett/Rspec-Tic-Tac-Toe/blob/227254dcbecfaff1d4f196d08737cce580fe563b/spec/game_manager_spec.rb#L4-L5), [this](https://github.com/Ispirett/Rspec-Tic-Tac-Toe/blob/227254dcbecfaff1d4f196d08737cce580fe563b/spec/gui_spec.rb#L4-L11) and [this ](https://github.com/Ispirett/Rspec-Tic-Tac-Toe/blob/227254dcbecfaff1d4f196d08737cce580fe563b/spec/player_spec.rb#L3)
Here I dd for `board_spec`


Also, remember one thing when you will use `let` always do it inside `RSpec.describe`. You can assign variable outside `RSpec.describe` when you need some `constant` variable. Please read this for know more about [better spec](http://www.betterspecs.org/).

You have almost tested all the important method of this project. So I will recommend you to also fix these problems and send another request to re-review this project. Let me know if you guys have any question without any hesitation you can ask me or share with me 🤗 

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @Ispirett  and @Macatuz ,
So far so good. But there are still some minor issues. Check out bellow: 

- in player_spec you forgot to use `let` for this `tom = Player.new('tom')`. So do the same thing you did for your previous ones like `Board`.
- in `spec\game_manager_spec.rb` you forget to require some libs like
```
require_relative '../lib/gui.rb'
```
That's why it's not working. So please fix it.

- in `spec\gui_spec.rb` you also forgot to require some dependencies like this

```
require_relative '../lib/player.rb'
require_relative '../lib/game_manager.rb'
```
I already mentioned about this in my previous feedback.

> rspec -f doc spec\gui_spec.rb is not working
> rspec -f doc spec\game_manager_spec.rb not working

Anyway, I think after fixing these issues you can merge it into the master. This is from me in advance 👍 

Thanks 🙏

**Comment by Ispirett** [comment]
Thank you solved the issues

**Pull request merged**
